create_clock -period 20.000 -name clk [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN N18 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property PACKAGE_PIN C20 [get_ports sclk]
set_property PACKAGE_PIN P19 [get_ports cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports cs_n]
set_property PACKAGE_PIN J15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports iic_scl]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports iic_sda]